[package]
name = "sedona_app"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
pollster = "0.4.0"
winit = { version = "0.30.8", features = ["android-native-activity"] }

sedona_resource = { path = "../sedona_resource" }
env_logger = "0.11.8"
